### ISSUE TITLE
Cant join a room with https

### ISSUE THREAD

**Issue by Jannik-Baar** [Rishabh-malhotraa/caucus#1]
If I try to join a room with https for example: https://caucus-app.herokuapp.com/room/public-room3 it show a white page

**Comment by Rishabh-malhotraa** [comment]
Thanks for pointing that out, its because my docker container does not have an SSL certificate, and you cannot receive data from an HTTP endpoint when requested from HTTPS, I think this could be solved with Nginx and reverse proxy, I look into fixing it soon after learning a bit about docket and Nginx.
