### ISSUE TITLE
Not supporting async functions in JavaScipt

### ISSUE THREAD

**Issue by CharlesElloit** [Rishabh-malhotraa/caucus#25]
The bug is, it doesn't support async arrow function or normal async function in JavaScript.
It automatically throws an error after running the function.

**Comment by Rishabh-malhotraa** [comment]
@CharlesElloit  thank you for pointing it out, this would be fixed in the next release PATCH 1.03, I'm a bit busy these days but basically, we need to migrate code execution from JDOODLE to the piston and that should take care of that, it would also add more languages for code execution like rust c swift etc..

**Comment by Rishabh-malhotraa** [comment]
async functions aren't supported by remote code execution engine, because the engine automatically destroys its docker instance after 2 seconds of runtime, so if the async function is not returned in 2 seconds it would not work.
